[Distribution]
Distribution=arch

[Build]
ToolsTree=default
WithNetwork=true
SandboxTrees=
        mkosi.sandbox:/
        /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist
        /etc/pacman.d/cachyos-mirrorlist:/etc/pacman.d/cachyos-mirrorlist
        /etc/pacman.d/cachyos-v3-mirrorlist:/etc/pacman.d/cachyos-v3-mirrorlist
        /etc/pacman.d/chaotic-mirrorlist:/etc/pacman.d/chaotic-mirrorlist
        /usr/share/pacman/keyrings:/usr/share/pacman/keyrings
        /etc/pacman.d/gnupg/trustdb.gpg:/etc/pacman.d/gnupg/trustdb.gpg

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=
Format=disk
ImageId=arcX
ManifestFormat=json
Output=%i_%v_%a

[Content]
RootPassword=root
UnifiedKernelImages=unsigned
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
Bootable=yes
Bootloader=systemd-boot
InitrdProfiles=
KernelInitrdModules=
        default
        erofs
Hostname=arcx

Packages=
        acl
        alacritty
        attr
        bash
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dms-shell
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        erofsfuse
        exfatprogs
        file
        findutils
        fish
        flatpak
        fwupd
        gdb
        gdisk
        glycin
        glycin-gtk4
        greetd-dms-greeter-git
        grep
        gzip
        jq
        kbd
        kexec-tools
        kimageformats
        kmod
        less
        linux-cachyos
        linux-firmware
        man
        mtools
        nano
        nautilus
        gvfs
        networkmanager
        nftables

        nix
        ntfs-3g
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        plasma-kde-applications
        pciutils
        pkcs11-provider
        polkit
	power-profiles-daemon
        quickshell
        sed
        socat
        strace
        sudo
        systemd
        tar
        tree
        udev
        udisks2
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xdg-desktop-portal-gtk
        xdg-desktop-portal-gnome
        wl-clipboard
        xxd
        yubikey-manager
        zip
        zlib-ng-compat
        zstd
        cava
        cups-pk-helper
        i2c-tools
        iwd
        matugen
        qt6-multimedia
        wtype

RemovePackages=linux

InitrdPackages=
        erofs-utils
        erofsfuse
        btrfs-progs

VolatilePackages=
        systemd
        udev

InitrdVolatilePackages=
        systemd
        udev

# [Validation]
# SecureBoot=yes
# SignExpectedPcr=yes

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
